#!/bin/bash

show_usage()
{
	echo "Usage:  -d build with debug option"
	echo "        -u build as unit test app"
	echo "        -s build static library"
	echo "        -c remove all build file"
    echo "        -D build wirh dbus session support"
    echo "        -L build libraries"
    echo "        -W build for win32"
	echo ""
	exit -1
}

show_message()
{
    echo "[-------------"$1"-----------------]"
}

BUILD_TYPE="Release"
UNIT_TEST="false"
PROJECT_CLEAN= "false"
BUILD_LIBS=0
OS_TYPE=`uname -s`
BUILD_ARCH=`uname -m`

if [ x"${OS_TYPE}" == x"Darwin" ];then
    DIR_ROOT=`pwd`
else
    DIR_ROOT=`realpath $(dirname "$0")`
fi

if [ -n "$1" ];then
if [ x"${1:0:1}" != "x-" ];then
  show_usage
fi
fi

if [ x"${OS_TYPE}" == x"Darwin" ];then
	echo "OS_TYPE is Darwin"
    export KERNEL_BITS=64
elif [ x"${OS_TYPE}" == x"Linux" ];then
    echo "OS_TYPE is Linux"
else
    echo "OS_TYPE is Windows"
	OS_TYPE="Windows"
    BUILD_ARCH="x64"
fi

while getopts 'cdsuj:LW' OPT; do
	case $OPT in
	c)
		PROJECT_CLEAN="true";;
	d)
		BUILD_TYPE="Debug";;
	u)
		UNIT_TEST="true";;
    j)
		JOBS=$OPTARG;;
    L)
		BUILD_LIBS="true";;
    W)
		BUILD_ARCH="Win32";;   
	?)
		show_usage
	esac
done
shift $(($OPTIND - 1))

#清理环境
if [ x"${PROJECT_CLEAN}" == x"true" ];then
	rm -rf ${DIR_ROOT}/tmp/ 2>&1 > /dev/null
    rm -rf ${DIR_ROOT}/out 2>&1 > /dev/null
	show_message "clean done"
	echo ""
	exit 0
fi

#环境准备
mkdir -pv ${DIR_ROOT}/out/include > /dev/null 2>&1
mkdir -pv ${DIR_ROOT}/out/lib > /dev/null 2>&1
mkdir -pv ${DIR_ROOT}/tmp/ > /dev/null 2>&1

#编译
if [ x"${JOBS}" == x"" ];then
    JOBS=`grep -c ^processor /proc/cpuinfo`
fi

if [ -z ${JOBS} ];then
    JOBS=1
fi

echo "decompress required libs for ${OS_TYPE}_${BUILD_ARCH}"
tar -xvf 3rd_party/${OS_TYPE}_${BUILD_ARCH}.tar.xz -C ${DIR_ROOT}/out > /dev/null 2>&1

#编译comex
cd ${DIR_ROOT}/tmp
if [ -d ${DIR_ROOT} ];then
  if [ x"$OS_TYPE" == x"Windows" ];then
      cmake -A ${BUILD_ARCH} -DBUILD_ARCH=${BUILD_ARCH} -DBUILD_TYPE=${BUILD_TYPE} -DUNIT_TEST=${UNIT_TEST} -DOS_TYPE=${OS_TYPE} ${DIR_ROOT} -DCMAKE_WIN32_WINNT=0x0600 && cmake --build . --target package --config ${BUILD_TYPE}
  else
      cmake -DBUILD_ARCH=${BUILD_ARCH} -DBUILD_TYPE=${BUILD_TYPE} -DUNIT_TEST=${UNIT_TEST} -DOS_TYPE=${OS_TYPE} ${DIR_ROOT} && make -j${JOBS} && make package
  fi
  if [ $? != 0 ]; then
    show_message "failed to make comex"
    exit -1
  fi
fi

show_message "succeed"
